잠이 안 와서 하는 커밋
wbluke/tistory-table-of-contents pull request #5
Opened 2019-12-29 21:31 UTC by kunggom

닉, 저 큰곰이에요. 아까 낮잠을 너무 잤다가 밤잠이 안 와서 새벽에 인터넷 좀 하다가 이 코드가 몇 군데서 소개되는 것을 보고, 생각난 김에 잠올 때까지 자바스크립트 좀 만져 봤어요. 제가 티스토리 블로그가 없어서 이렇게 바꾼 코드가 완전히 제대로 돌아갈지 모르겠는데, 아마 제대로 돌아갈 거라고 생각해요.

2019-12-30 01:27 UTC, wbluke requested changes
안녕하세요 큰곰! 와 제 코드에 관심가져주시고 리팩토링 해주셔서 감사해요ㅠㅠ 귀한 가르침을 받았네요.
제가 오늘 일정이 있어서 아직 동작하는 코드인지는 테스트를 못해보고 일단 마음에 걸리는 부분에서만 리뷰를 남겨봤어요
답변 주시면 오늘 밤이나 내일 오전에 확인하고 테스트한뒤에 merge해보겠습니다! :)

2019-12-30 01:27 UTC, wbluke commented on toc.js
> -      hTags = mainContents.querySelectorAll('h1, h2, h3');
`hTag`의 초기화 로직을 존재성 체크 뒤에 둔 이유는 querySelector로 잡아온 `mainContents`라는 부분이 스킨에 따라 없을 수도 있기 때문이에요ㅠ 하지만 최근의 수정으로 mainContents를 사용자가 직접 수정하도록 해당 클래스를 가장 상단의 상수로 빼놓아서, 어떻게 두는 게 나을지 고민이네요. 그래도 방어적으로 남겨두기 위해 hTags는 lazy하게 초기화하는게 좋지 않을까 싶어요! 어떻게 생각하시나요?ㅎㅎ

2019-12-30 01:27 UTC, wbluke commented on toc.js
> +      onscroll,
헉 이런게 되는군요 +_+

2019-12-30 01:27 UTC, wbluke commented on toc.js
> +      return [...hTags].reduce((pre, cur) => {
처음 보는 문법이네요. 좋은걸 배워갑니다 :)

2019-12-30 04:02 UTC, kunggom commented on toc.js
> -      hTags = mainContents.querySelectorAll('h1, h2, h3');
`hTags`를 `checkExistenceOfHTags()` 함수 안에서 초기화시키는 것은 명백히 한 함수 내에서 여러 일을 하는 것이라 논란의 여지 없이 다른 곳으로 빼야 한다고 생각해요. 제가 `hTags`의 초기화를 바깥으로 뺀 것도 코드의 다른 부분을 봐서 별 문제가 없을 것 같다고 판단했기 때문이지요. 어차피 `mainContents`가 없는 환경에서는 코드가 작동하지 않을 테니까요. 만약 정 `hTags`를 나중에 초기화해야 한다고 생각한다면, 그 부분만 전담하는 함수를 따로 하나 만드는 게 맞다고 봐요.

2019-12-30 04:03 UTC, kunggom commented on toc.js
> +      onscroll,
네. ES6 객체 리터럴의 단축 표기법인데, 우테코 하면서 보니까 다들 다른 ES6 문법은 잘들 쓰면서 이건 왠지 잘 안 쓰더라고요. 근데 이런 패턴이 자주 쓰이기 때문에 알아두면 정말 좋아요.

2019-12-30 04:05 UTC, kunggom commented on toc.js
> +      return [...hTags].reduce((pre, cur) => {
이것도 ES6 문법입니다. 자바스크립트가 ES6에서 상당히 바뀌었어요. Java로 비유하자면 Java 8 정도.

2019-12-31 02:43 UTC, wbluke commented on toc.js
> -      hTags = mainContents.querySelectorAll('h1, h2, h3');
그렇네요. 말씀해주신 부분에 동의합니다 :) 
다만 mainContents를 querySelector로 잡아오는 부분도 같이 빼야 할 것 같은데 이건 제가 수정할게요.

2019-12-31 03:07 UTC, merged